// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE1aOCtu6e267C-T4EQ-_9EY0O7LV9qyE',
    appId: '1:520290534471:web:a9f33a8529db3695b89d62',
    messagingSenderId: '520290534471',
    projectId: 'test-flutter-31a73',
    authDomain: 'test-flutter-31a73.firebaseapp.com',
    storageBucket: 'test-flutter-31a73.appspot.com',
    measurementId: 'G-H1LNNR82MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMVls-MxgADnPMJlIfALR47V-gVwPQTDI',
    appId: '1:520290534471:android:cc7bf1cdbb28d732b89d62',
    messagingSenderId: '520290534471',
    projectId: 'test-flutter-31a73',
    storageBucket: 'test-flutter-31a73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEEDK3pghNc9dFVMGA3g6X0Z7lfYcM67c',
    appId: '1:520290534471:ios:7e9e383599b4d341b89d62',
    messagingSenderId: '520290534471',
    projectId: 'test-flutter-31a73',
    storageBucket: 'test-flutter-31a73.appspot.com',
    iosClientId: '520290534471-rn9irflu1ugmnkdrkmm93bke51gbb7gk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEEDK3pghNc9dFVMGA3g6X0Z7lfYcM67c',
    appId: '1:520290534471:ios:7e9e383599b4d341b89d62',
    messagingSenderId: '520290534471',
    projectId: 'test-flutter-31a73',
    storageBucket: 'test-flutter-31a73.appspot.com',
    iosClientId: '520290534471-rn9irflu1ugmnkdrkmm93bke51gbb7gk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
